Add files via upload

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,7 +6,7 @@
 #      ▇▇          ▇ @UU_iv   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
 #      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @UU_iv
 #      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @UU_iv  ▇▄                 ▇▇                 ▇▇
-#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source Google BY @UU_iv
+#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source kgt BY @UU_iv
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
  
@@ -27,11 +27,11 @@ echo -e "${GREEN}
 ▇▇          ▇ @UU_iv   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
 ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @UU_iv
 ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @UU_iv  ▇▄                 ▇▇                 ▇▇
-▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source Google BY @UU_iv
+▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source kgt BY @UU_iv
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Google 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source kgt 
 ${CNIL}";
 exit;
 fi
@@ -41,7 +41,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source Google${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source kgt${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -70,10 +70,10 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "Google"; then
-screen -S Google ./run R
+if ! screen -list | grep -q "kgt"; then
+screen -S kgt ./run R
 fi
-screen -S Google -X kill
-screen -S Google ./run R
+screen -S kgt -X kill
+screen -S kgt ./run R
 fi
 
